language: node_js
node_js:
  - "5.8"
services:
  - docker
cache:
  directories:
    - node_modules
    - .nvm
before_script: touch .env
script: npm run coveralls

env:
  global:
    - secure: "iiOMOOVt6UXVF32BakPXWuU3sqDMOZpZ3XZZ9lvw7vhnNtpvABu6bvYf/r1FhtHx2BqGmrONYE2argwkKYX7Az6ZsT+xbdAa7Qj86H3hOoTk7A/chhXmaeTU7DMuSeZt0i3GbZ8IpMWQYRm9db/b2RHA1RvV9QsCAGcaVeIU4KC1uSc18qpv6CkppKC4eilBuuN1JYtcAbwyZuAn8GUMdQDzf6aVCZCuaRgLWhSnS6mf/zAFw+Ypd6nxdCTW2uQQmMiqaOGzCD+65c+kVS6fGjvH1MPjJJzZRsiYDtWuA+QZJ/F9GVpyBq+7JzPh9TbKL8eSouNqD3NoDW1vSB/FqQg5DiW1X2L5AisdJz5LoXYxOvkxKTJ2mHGnsM8pjm2VOjvvBA3I3Wlarwv56c9KQqTijUp3j8JCU7GJGo5qK8jhanidGPPwJr887CL11taI/56j+2hQAoJyHHsvhEDdWlGXTuked4t5h1xCx/kFKZJsl9i4bsLXkQZbp4ZuogSNUpBfgw6H/9f/x8AzGUinhN8sob+4euuF9Zhmi8eUee7nSFpQyh94Hi2JmWawYPzoqRvBhVe39zjxvC8yQzZAK1w9sSD0LYKYd5esVbJEiilyNXmhX6GVv5vQwPv6ay0i8cYXFgqMN3xnXFIaKhfah1xHADOLTZ1G7NCYB7Yv66A="
    - secure: "JKNCrvy9GEXhuwoha/IDFi5yDMUK0dOk/yhCuZeOQWuaTKelnlS9IrnZUmvioYRwzoZVWYv6eGoe7+o/jDq/0Qiu/2dBgnVxoD0KE5Fnd/ZLE7op60GYDsS+EYrwIH2zW99yR9DSwgutEh3YyBr1u869aMQxoeHsaEVl4ZJU4pmIc19lAe/TEl0kSBolezvO8etFGNV9ErydsqfdKRHY/JirGXj0QiBf1MhOKSYzC95elnjsH2S2um+3lwSvMcWRShGX37KnXkyfAzgxKHm2Bsqvid2VSJPnhajk8RZ0HJmjCNdlfXMiGC9CsFnWitFXA2kDJ+tgjO86mtIlNT/bbwS88k/S+Of+HdLnaR+89sig5KoYQGLxDAPpWDDYutKBRULiCxVLvWObXu3sjouPhn+v6TIl4q6+eC61+9ODH/b0cdt2tzy7w2AdkOs2oasu8g8uURawYjPTJeE0kP/Tx/78P8MeyS6/EUsc3mtHg9qC10m/abUl0fvomlzmLSFul8d2HwuSp7bPjtK24VAqPc2vB1U3VpxlaS2B0i3IxwOs+LQmsNKezMa1DpJl1kdpj0ahcQw9AtOVMKw+t1QB0ClB3RzQQu2LuEqRIwHLBZLloEUzVFG8e//0fjSk7Oru6uhdQ+q2EZxTT33v58m8Q3N4zsLC2Pz00dX+zKbnDuE="
    - secure: "pn3fKhIlmG2wzwyFt/oiW+Ny0Bu13coknhzCciBZHn75zeE1LNCgcmfXdXdk3OZWTbR9SGaJzywescnCCr7fIdlXa9XLq0I3GYYjMZzc1JvTOV0QrvW3ttXot+Su3ewg55WtAfCq52oIY5A8cWZblz+cUQyuWKr/Iy2lo8k6QWabxsJrpWZVzbfQFvk3SDPDQWmITHmZyyi2wZG7v/+xZYqNsBV5y29iM5NgsyOqosY+eKQ2pFZErnAYREStnnR7LuDMwwYT53Nl1h7JVWkBYuI3DINEgi/fT4h1Zd1DT/wr8BsH5sMKSmHdeZ489ozhM/itDN6LQ3QPx3/YUL9mRGROWMqVSgxABZr0ZxA1w3zy3D12p0DKrDJNbmx4Wjzw7ZcX0JcltdWieC+ytZTFCwYLPNRSuJLps83ZiGREgJS0lXG9PgXfzDI57MYczXpyb4qDCIO3+miVsQyCUKs3UTtocUO2ZhBEBpx1783mYW6TbBfg1qUpd9z7Y7ADgpfVzkhpGVogU5XosDIBWrhzicUdBOLiQQ/9kmnIyjG1HWL4UGAN0jbuQWL8vIrRcsp/jHeud77Hde/vuQ8TxHkiOpS9G3H4VLCxG5gqqSxoYVKygP7WnvBaP2LBbwPnM878uIg49CAnWnRDY/8eEX/P5bBZU4zfELb9dr1id9yJ0c0="

before_deploy:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t opentrials/opentrials:$TRAVIS_COMMIT .
deploy:
  provider: script
  script: docker push opentrials/opentrials
  on:
    condition: "$TRAVIS_PULL_REQUEST == false"
    branch: master
